edited Phyflex setup

diff --git a/test~ b/test~
--- a/test~
+++ b/test~
@@ -1,7 +1,63 @@
  
 #!/bin/bash
 # init
-function pause(){
+
+DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
+
+sudo $DIR/tftp_setup.sh
+
+ReloadPackages="false"
+
+PhyflexDir=0
+ReloadPackages="false"
+for i in "$@"
+do
+case $i in
+    -d|--download)
+    ReloadPackages="true"
+    ;;
+    -p=*|--path=*)
+    PhyflexDir="${i#*=}"
+    ;;
+    # -l=*|--lib=*)
+    # DIR="${i#*=}"
+    # ;;
+    # --default)
+    # DEFAULT=YES
+    # ;;
+    *)
+            # unknown option
+    ;;
+esac
+done
+echo $ReloadPackages
+eval PhyflexDir=$PhyflexDir
+echo $PhyflexDir
+
+if [ -x "/usr/local/lib/ptxdist-2011.11.0/bin/ptxdist" ]; then
+ echo "WHAAHHAHAHAHAHAHAHAHAHHAHAHAHAHA"
+else
+ echo "NOOOOOOO"
+fi
+
+apt-get install tftpd-hpa
+
+#Erase /etc/default/tftpd-hpa and replace its contents with the following
+> /etc/default/tftpd-hpa
+cat >/etc/default/tftpd-hpa<<EOL
+# /etc/default/tftpd-hpa 
+
+TFTP_USERNAME="tftp"
+#TFTP_DIRECTORY="/var/lib/tftpboot"
+TFTP_DIRECTORY="${PhyflexDir}/BSP-Phytec-phyFLEX-i.MX6-PD13.2.3BSP-Phytec-phyFLEX-i.MX6-PD13.2.3/platform-phyFLEX-i.MX6/images"
+TFTP_ADDRESS="0.0.0.0:69"
+TFTP_OPTIONS="--secure"
+EOL
+
+
+
+function pause()
+{
    read -p "$*"
 }
 
@@ -22,19 +78,74 @@ function valid_ip()
     return $stat
 }
 
-echo "You will need a valid Static IP address inside your network to dedicate to to the Phyflex i.MX6. You should contact your network adminstrator to get one. If you have already gotten one, then you can enter it now. Or you can enter [d] to "
-read BoardStaticIP
 
 
-if (valid_ip $BoardStaticIP); then
-  echo "$BoardStaticIP"
-elif($BoardStaticIP=="d");then
-	#get your ip address
-	ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
-	sudo nmap -v -sn -n $ip/24 -oG - | awk '/Status: Down/{print $2}'
+
+
+
+
+apt-get install minicom
+
+
+wget $wgetargs -O $HOME/ptxdist-2011.11.0.tar.bz2 'http://www.pengutronix.com/software/ptxdist/download/ptxdist-2011.11.0.tar.bz2'
+
+echo 
+echo "You will need a valid Static IP address inside your network to dedicate to to the Phyflex i.MX6. You should contact your network adminstrator to get one. If you have already gotten one, then you can enter it now. Or you can enter [d] to generate a list of available ip addresses on your ethernet network, and then pick one you like."
+OK=0
+BoardStaticIP=0
+#Get the Host's IP address
+ip=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
+while [ $OK -lt 1 ]; do
+  echo "Enter a valid Static IP:"
+  read BoardStaticIP
+  if (valid_ip $BoardStaticIP); then
+    echo "IP is valid: $BoardStaticIP"
+    OK=1
+  # elif ("$BoardStaticIP" == "d"); then
+  elif [ "$BoardStaticIP" == "d" ]; then
+  	#get your ip address
+  	sudo nmap -v -sn -n $ip/24 -oG - | awk '/Status: Down/{print $2}'
+  else
+    	echo "Invalid IP"
+  fi
+done
+printf "Configuring project files for Host: %s and Board: %s...\n" "$ip" "$BoardStaticIP"
+
+echo "Restart you Phyflex.iMX6 with minicom running on the Host and press m before the board counts down to 0 to enter the barebox menu. Then go to settings->network set your network settings on the board to the following:"
+echo
+echo "ipaddr=$BoardStaticIP"
+echo "netmask=255.255.255.0"
+echo "gateway=$ip"
+echo "serverip=$ip"
+echo 
+echo "Then you will need to boot the board"
+echo "Pinging Static IP: $BoardStaticIP"
+echo
+
+
+OK=0
+while [ $OK -lt 1 ]; do
+  ping -c 1 "$BoardStaticIP" 2>&1 >/dev/null; alive=$?
+  if [ "$alive" == "0" ]; then
+    echo "Static IP ping was sucessful: $BoardStaticIP"
+    OK=1
+  else
+      pause "Failed to ping Static IP please make sure that the network setting on the board are set correctly. Press Enter to try again continue..."
+  fi
+done
+
+if [ -a "$HOME/.ssh/id_rsa.pub" ]; then
+  echo "Public key found..."
 else
-  echo "Invalid IP"
+  echo 
+  echo "Running ssh-keygen to build a public ssh key..."
+  echo
+  ssh-keygen -t rsa -b 4096
 fi
+
+
+
+
 
 : <<'COMMENT'
 #get your ip address
